Repository Vactor0911/jobtalk, pull requests merged in 2025-09, with the labels that each got.

#51 README 내용 수정
  README.md
Labels: 문서화

#52 README 역할명 수정
  README.md
Labels: 문서화

#56 kst 날짜 파싱 함수 제거
  frontend/src/pages/MyWorkspace.tsx
  frontend/src/utils/index.ts
Labels: 버그

#57 헤더의 토큰과 쿠키의 토큰 여부 확인
  backend/src/utils/csrfUtil.ts
Labels: 개선

#59 csrf 토큰 커스텀 비교 로직 제거 및 자동 검증 로직 추가
  backend/package-lock.json
  backend/package.json
  backend/src/index.ts
  backend/src/routes/authRoute.ts
  backend/src/routes/chatRoute.ts
  backend/src/routes/workspaceRoute.ts
  backend/src/utils/csrfUtil.ts
  backend/src/utils/index.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/utils/axiosInstance.ts
  frontend/vite.config.ts
Labels: 버그

#62 쿠키 사용 안내 문구 추가
  frontend/src/pages/Login.tsx
Labels: 개선
